### DISCUSSION TITLE
Rate limiting over multiple services

### DISCUSSION THREAD

**Discussion by shadowzer** [vladimir-bukhtoyarov/bucket4j#524] [Q&A] [answered]
Hello there. I've tried to resolve next issue: lets assume we have 3rd party API, which called from 2 microservices with several pods in Openshift distributed environment. 3rd party API have bandwidth limit for stable working, let's say it's 25 requests per second. I've chosen distributed bucket4j implementation with lettuce redis client (com.bucket4j:bucket4j_jdk17-redis-common:8.14.0  +  com.bucket4j:bucket4j_jdk17-lettuce:8.14.0). Both services have same configuration:
```    
@Bean
    public Bucket rateLimiterBucket(RedisProperties redisProperties) {
        var redisClient = RedisClient.create(RedisURI.builder()
                .withHost(redisProperties.getHost())
                .withPort(redisProperties.getPort())
                .withDatabase(redisProperties.getDatabase())
                .withSsl(redisProperties.isSsl())
                .withTimeout(redisProperties.getTimeout())
                .build());
        var proxyManager = Bucket4jLettuce.casBasedBuilder(redisClient)
                .expirationAfterWrite(
                        ExpirationAfterWriteStrategy.basedOnTimeForRefillingBucketUpToMax(Duration.ofSeconds(30)))
                .build();
        var key = rateLimiterProperties.getBucketName().getBytes(StandardCharsets.UTF_8);
        return proxyManager.getProxy(key, this::rateLimiterBucketConfiguration);
    }
    private BucketConfiguration rateLimiterBucketConfiguration() {
        return BucketConfiguration.builder()
                .addLimit(limit -> {
                    var builder = limit.capacity(rateLimiterProperties.getCapacity());
                    return rateLimiterProperties.getRefillStrategy() == RateLimiterProperties.RefillStrategy.GREEDY
                            ? builder.refillGreedy(rateLimiterProperties.getRefillTokens(), rateLimiterProperties.getRefillDuration())
                            : builder.refillIntervally(rateLimiterProperties.getRefillTokens(), rateLimiterProperties.getRefillDuration());
                })
                .build();
    }
```

Rate limiting code:
```
            if (bucket.asBlocking().tryConsume(1, rateLimiterProperties.getTokenMaxWaitDuration())) {
                // success business logic
            } else {
                // business logic for no available token
            }
```
serviceA config:
```
    rate-limiter:
      bucket-name: rate-limiter-bucket
      capacity: 30
      token-max-wait-duration: 750ms
      refill-strategy: GREEDY # GREEDY / INTERVAL
      refill-tokens: 15
      refill-duration: 1s
```
serviceB config:
```
    rate-limiter:
      bucket-name: rate-limiter-bucket
      capacity: 30
      token-max-wait-duration: 750ms
      refill-strategy: GREEDY # GREEDY / INTERVAL
      refill-tokens: 10
      refill-duration: 1s
```
So we split our available 25 rps (tokens) to refill between 2 services (15 + 10). When services used they own bucket (unique redis key per service) - all works great, as expected.

Expected behavior when 2 services using common bucket: since both services using common bucket (redis key in this case), so capacity is common for both services, and both services refilling tokens, then bandwidth is shared between two services. When payload is coming to only serviceA, it takes 30 tokens for the 1st second (since bucket created with full capacity), then starting from 2nd second it takes 25 tokens (since serviceA refilling 15 tokens per sec & serviceB refilling 10 tokens per sec).

Actual behavior when 2 services using common bucket: When payload is coming to only serviceA, it takes 30 tokens for the 1st second (since bucket created with full capacity), then starting from 2nd second it takes only 15 tokens. So serviceA cannot take refilling bandwidth of the serviceB.

I suppose there is some local optimization code in the lib, which only knows about his own refilling, and ignores that some other service is refilling same bucket too.
Please, help me understand, is my issue resolvable by this lib? Or my case does not supported by the lib architecture?
